name       : pulseaudio-qt
version    : 1.1.0
release    : 1
source     :
    - https://cdn.download.kde.org/stable/pulseaudio-qt/pulseaudio-qt-1.1.0.tar.xz : 9c7cbc484dee6ab6bd6b479a5cca14c7f38a4d020f03e99ecfd047136da18662
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Qt framework C++ bindings library for the PulseAudio sound system
description: |
    Qt framework C++ bindings library for the PulseAudio sound system
builddeps  :
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
