name       : pulseaudio-qt
version    : '1.3'
release    : 3
source     :
    - https://cdn.download.kde.org/stable/pulseaudio-qt/pulseaudio-qt-1.3.tar.xz : bceb07630d946fa0ce928b177687f618186cdef2309828188211d61a36589ec4
license    : LGPL-3.0-only
component  : desktop.kde
summary    : Qt framework C++ bindings library for the PulseAudio sound system
description: |
    Qt framework C++ bindings library for the PulseAudio sound system
builddeps  :
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
